version: '3.4'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
      #- KEYCLOAK_FRONTEND_URL=https://8080-pucrspoli-constrsw20222-j5tvhlb4zz6.ws-us65.gitpod.io/auth
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
      - ./keycloak-realm-export.json:/tmp/realm.json
    command:
      # jboss/keycloak realm import doesn't work at all
      - -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    networks:
      - grupo3
networks:
  grupo3:
    external: true
volumes:
  keycloak-data:
