version: '3.4'
services:
  keycloak-api:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - KEYCLOAK_REALM=master
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_RESOURCE=grupo3
      - KEYCLOAK_SECRET=UHnzM10qJ5j2PZjIqaMwMKrA81r2vqpW
    networks:
      - grupo3
networks:
  grupo3:
    external: true
