name: Integration Tests
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create docker networks
        run: npm run up:network
      - name: Create docker volumes
        run: npm run up:volumes
      - name: Up all
        run: npm run up
      - name: Install dependencies
        working-directory: ./tests
        run: npm ci
      - name: Integration test
        working-directory: ./tests
        run: npm t
